### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by naokikob** [hopv/hoice#28]
For the following input:

-------------------
(set-logic HORN)
(declare-fun X (Int Int) Bool)
(declare-fun F (Int Int) Bool)
(declare-fun Entry_ () Bool)
(assert (forall ((A Int) (B Int) (C Int) (D Int))
  (let ((a!1 (and (F B A) (= A (* 2 C D)) (= B (+ (* C C) (* D D))))))
    (=> a!1 (X C D)))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X B A) (= A (- C 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X B A) (= A (+ C 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X A C) (= A (- B 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X A C) (= A (+ B 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int) (D Int))
  (=> (and (F B A) (= A (- D 1)) (= B (- C 1)) (> D 0)) (F C D))))
(assert (forall ((A Int) (B Int)) (=> (< A 0) (F A B))))
(assert (forall () (=> (X 0 0) Entry_)))

(assert (forall () (not Entry_)))
(check-sat)
(exit)

-----------------
Hoice produces the following error:
(error "
  solver error: "line 454 column 57: unknown function/constant F"
")

**Comment by AdrienChampion** [comment]
I cannot reproduce this problem on macos. I do not have access to a machine running windows right now, but I will by the end of the week.

The problem actually from z3, below hoice. Can you tell me which version of Z3 you are running? Can you try with 4.7.1 if that's not already the version you're running?
You can also run with `--smt_log on` which will dump all communications with z3 in a `hoice_out` directory. If you have time, you can run hoice with this option and look at/send me the `smt2` files that it dumps.

**Comment by AdrienChampion** [comment]
Never mind, I was not letting hoice run long enough. The upcoming PR will fix the problem.
