### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by naokikob** [hopv/hoice#29]
Running
hoice foo.smt2 --timeout 1
produces the error:
(error "
  Broken pipe (os error 32)
  from ice learner
")

for the following input foo.smt2:

(set-logic HORN)
(declare-fun X (Int Int) Bool)
(declare-fun F (Int Int) Bool)
(declare-fun Entry_ () Bool)
(assert (forall ((A Int) (B Int) (C Int) (D Int))
  (let ((a!1 (and (F B A) (= A (* 2 C D)) (= B (+ (* C C) (* D D))))))
    (=> a!1 (X C D)))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X B A) (= A (- C 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X B A) (= A (+ C 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X A C) (= A (- B 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X A C) (= A (+ B 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int) (D Int))
  (=> (and (F B A) (= A (- D 1)) (= B (- C 1)) (> D 0)) (F C D))))
(assert (forall ((A Int) (B Int)) (=> (< A 0) (F A B))))
(assert (forall () (=> (X 0 0) Entry_)))

(assert (forall () (not Entry_)))
(check-sat)
(exit)

**Comment by AdrienChampion** [comment]
I cannot reproduce the problem on macos. I will look into it as soon as I have access to a machine running windows, in  a few days. See also my answer to #28.

**Comment by AdrienChampion** [comment]
The problem seems to be that when hoice runs with a timeout, it runs z3 with a timeout. In your example, I think z3 was timeout-ing during a check, causing it to die, and then the learner tried to do something with the now-dead-solver.
The error was benign however, hoice was still saying `timeout` right after the error.

For the record, here are the clauses with which I managed to reproduce the bug

```
(set-logic HORN)
(declare-fun X (Int Int) Bool)
(declare-fun F (Int Int Int) Bool)
(declare-fun P!!1 (Int Int Int) Bool)
(declare-fun Entry_ () Bool)
(assert (forall ((A Int) (B Int) (C Int))
  (let ((a!1 (>= A (+ (+ 16 (* 16 B)) (* (- 16) C))))
        (a!2 (>= A (+ (+ 16 (* (- 16) B)) (* 16 C))))
        (a!3 (>= A (+ (+ 16 (* (- 16) B)) (* (- 16) C))))
        (a!4 (>= A (+ (+ 16 (* 16 B)) (* 16 C)))))
    (=> (and (F A B C) a!1 a!2 a!3 a!4) (X B C)))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X B A) (= A (+ C 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (and (X A C) (= A (+ B 1))) (X B C))))
(assert (forall ((A Int) (B Int) (C Int) (D Int))
  (=> (and (P!!1 D C B) (F A D C) (= A (- B 1)) (not (= D 0))) (F B C D))))
(assert (forall ((A Int) (B Int) (C Int) (D Int) (E Int))
  (=> (and (F B A E) (= A (- D E)) (= B (- C 1))) (P!!1 E D C))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (< B C) (P!!1 C B A))))
(assert (forall ((A Int) (B Int) (C Int)) (=> (<= A 0) (F A B C))))
(assert (forall () (=> (X 0 0) Entry_)))

(assert (forall () (not Entry_)))
(check-sat)
(exit)
```
