### ISSUE TITLE
parse error on CHCs with ground assertions

### ISSUE THREAD

**Issue by hgvk94** [hopv/hoice#52]
I get the following parse error when CHC have ground assertions:
``` expected forall or negated exists ```

[example](https://gist.github.com/hgvk94/dbe06d519440c5bc9745189b25bdc865)
[commit](https://github.com/hopv/hoice/commit/baf8050a023514c3cf638df126269e7b85860217)

**Comment by AdrienChampion** [comment]
Thank you for your feedback, the problem should be fixed now :)
